/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CompaniesRouteImport } from './routes/companies'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CompaniesCorpCodeSummaryRouteImport } from './routes/companies.$corpCode.summary'

const CompaniesRoute = CompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesCorpCodeSummaryRoute =
  CompaniesCorpCodeSummaryRouteImport.update({
    id: '/$corpCode/summary',
    path: '/$corpCode/summary',
    getParentRoute: () => CompaniesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/companies': typeof CompaniesRouteWithChildren
  '/companies/$corpCode/summary': typeof CompaniesCorpCodeSummaryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/companies': typeof CompaniesRouteWithChildren
  '/companies/$corpCode/summary': typeof CompaniesCorpCodeSummaryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/companies': typeof CompaniesRouteWithChildren
  '/companies/$corpCode/summary': typeof CompaniesCorpCodeSummaryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/companies' | '/companies/$corpCode/summary'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/companies' | '/companies/$corpCode/summary'
  id: '__root__' | '/' | '/companies' | '/companies/$corpCode/summary'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompaniesRoute: typeof CompaniesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/companies': {
      id: '/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof CompaniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies/$corpCode/summary': {
      id: '/companies/$corpCode/summary'
      path: '/$corpCode/summary'
      fullPath: '/companies/$corpCode/summary'
      preLoaderRoute: typeof CompaniesCorpCodeSummaryRouteImport
      parentRoute: typeof CompaniesRoute
    }
  }
}

interface CompaniesRouteChildren {
  CompaniesCorpCodeSummaryRoute: typeof CompaniesCorpCodeSummaryRoute
}

const CompaniesRouteChildren: CompaniesRouteChildren = {
  CompaniesCorpCodeSummaryRoute: CompaniesCorpCodeSummaryRoute,
}

const CompaniesRouteWithChildren = CompaniesRoute._addFileChildren(
  CompaniesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompaniesRoute: CompaniesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
